root URL redirects to current
jakartaee/jakartaee-documentation-ui pull request #26
Opened 2023-11-21 12:52 UTC by jhammen

#24

2023-11-21 19:57 UTC, kito99 requested changes

2023-11-21 19:57 UTC, kito99 commented on src/static/jakartaee-tutorial/index.html
> +window.location.replace('https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/');
How does this compare to the meta [equiv approach](https://www.w3schools.com/tags/att_meta_http_equiv.asp)?

I can't think of why this wouldn't work, though. If they don't have JS enabled probably nothing will work anyway.

Should perhaps they be relative links?

2023-11-22 02:34 UTC, kito99 commented
@jhammen this might be the Antora-specific way to do this (in the `jakarta-documentation`) repo: https://docs.antora.org/antora/latest/playbook/site-start-page/

2023-11-22 11:13 UTC, jhammen commented
> @jhammen this might be the Antora-specific way to do this (in the `jakarta-documentation`) repo

you're right - I just tried that and it auto-generated a similar index file using meta equiv :)

closing this PR, will make another one in the jakarta-documentation repo

2023-11-22 11:13 UTC, closed without merging