Add Eclipse Foundation cookie consent to template
jakartaee/jakartaee-documentation-ui pull request #28
Opened 2024-01-17 20:22 UTC by autumnfound

As requested in https://github.com/jakartaee/jakartaee-documentation/issues/20, a cookie consent banner will be added to the core template of the site in compliance with privacy laws in enabling Google Analytics.

2024-01-18 16:55 UTC, kito99 requested changes
GTM changes need do be done here rather than being hardcoded in the template: https://docs.antora.org/antora/latest/playbook/site-keys/#google-analytics-key

2024-01-18 18:22 UTC, autumnfound commented
> GTM changes need do be done here rather than being hardcoded in the template: https://docs.antora.org/antora/latest/playbook/site-keys/#google-analytics-key

From what I understand, this repository override the areas where the base UI implements GTM, so it differs from the built-in implementation. I can remove the changes and make a secondary change to add a googleAnalytics key to the playbook instead though and see if the current code works!

I've reverted the change so we should otherwise be good to go here.

2024-01-19 01:13 UTC, kito99 approved these changes

2024-01-19 01:15 UTC, merged

2024-01-19 02:10 UTC, kito99 commented
@autumnfound this has now been deployed, but I don't see anything on the page (although I can see the changes in the page); should I?

2024-01-22 16:24 UTC, autumnfound commented
> @autumnfound this has now been deployed, but I don't see anything on the page (although I can see the changes in the page); should I?

Looking at production, I can see the cookie banner now. It might be that it sees an acceptance in your cookies which is how we stop it from popping up constantly.
 
![image](https://github.com/jakartaee/jakartaee-documentation-ui/assets/23018241/38a1dcde-eca9-420a-9898-22233ba140c2)

WRT the analytics, I'm not seeing that on production even though I see it in the code when I do a local build and add the same configuration we have there to the preview config. I'm not really sure what's the problem there, as I've never used Antora before this patch and only have experience in similar systems like Hugo